export const FETCH_ALL_SHIFTS = 'FETCH_ALL_SHIFTS';
export const FETCH_PAUSED_SHIFTS = 'FETCH_PAUSED_SHIFTS';
export const ADD_TRANSACTION_TO_SHIFT = 'ADD_TRANSACTION_TO_SHIFT';
export const ADD_EVENT_TO_SHIFT= 'ADD_EVENT_TO_SHIFT';
export const PRINT_RECEIPT= 'PRINT_RECEIPT';